Learning numpy

In [8]:
import numpy as np

In [15]:
#printing 1-D array
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [14]:
#to print version
print(np.__version__)

2.2.5


In [11]:
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [13]:
#Use a tuple to create numpy array
arr=np.array((1,2,3,4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [17]:
# 0-D array
arr=np.array(42)
print(arr)

42


In [20]:
#2-D array
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [21]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,4,5]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 4 5]]]


In [24]:
#Check number of dimensions
a=np.array(42)
b = np.array([1, 2, 3, 4, 5])
c=np.array([[1,2,3],[4,5,6]])
d= np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,4,5]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [26]:
#Create an array with 5 dimensions and verify that it has 5 dimensions
arr = np.array([1,2,3,4,5],ndmin=5)
print(arr)
print('number of dimensons:',arr.ndim)

[[[[[1 2 3 4 5]]]]]
number of dimensons: 5


In [ ]:
# 1-D array representation
arr=np.array([1,2,3,4,5])
print(arr[0])

1


In [ ]:
#1-D array sum
arr=np.array([1,2,3,4,5])
print(arr[0]+arr[1])

3


In [ ]:
#2-D array
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row:',arr[0,1])

2nd element on 1st row: 2


In [ ]:
#3-D array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


In [ ]:
#Negative Dimensions
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [7]:
#Slicing
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [8]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


In [9]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


In [10]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


In [11]:

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [12]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


Slicing in 2D Array

In [13]:
arr= np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])

[7 8 9]


In [14]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2,2])

[3 8]


In [15]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


DataTypes

In [16]:
arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int64


In [18]:
arr=np.array(['apple','banana','cherry'])
print(arr.dtype)

<U6


In [21]:
#Creating array with defined DataType
arr=np.array((1,2,3,4), dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [22]:
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [ ]:
#ValueError
arr = np.array(['a', '2', '3'], dtype='i')

ValueError: invalid literal for int() with base 10: 'a'

In [25]:
#Converting datatypes on existing arrays
arr=np.array([1.1,2.2,3.3])
newarr=arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [26]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int64


In [28]:
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [30]:
#The copy SHOULD NOT be affected by the changes made to the original array.
arr=np.array([1,2,3,4,5])
x=arr.copy()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [31]:
#The view SHOULD be affected by the changes made to the original array.
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [32]:
arr=np.array([1,2,3,4,5])
x=arr.view()
arr[0]=31
print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [ ]:
#The copy returns None.
#The view returns the original array.
arr=np.array([1,2,3,4,5])
x=arr.copy()
y=arr.view()
print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [ ]:
#Get the Shape of an Array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [ ]:
#at index-4 we have value 4, so we can say that 5th ( 4 + 1 th) dimension has 4 elements.
arr=np.array([1,2,3,4], ndmin=5)
print(arr)
print('shape of the array:',arr.shape)

[[[[[1 2 3 4]]]]]
shape of the array: (1, 1, 1, 1, 4)


In [36]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Reshape From 1-D to 3-D

In [ ]:
#The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
#3*3=9 elements
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(3, 3)

print(newarr)

ValueError: cannot reshape array of size 8 into shape (3,3)

In [ ]:
#Returns Copy or View=>return original array so it is a view
arr=np.array([1,2,3,4,5,6,7,8])
print(arr.reshape(2,4).base)

[1 2 3 4 5 6 7 8]


In [40]:
#Unknown Dimensions
arr=np.array([1,2,3,4,5,6,7,8])
newarr=arr.reshape(2,2,-1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [41]:
arr=np.array([[1,2,3],[4,5,6]])
newarr=arr.reshape(-1)
print(newarr)


[1 2 3 4 5 6]


In [ ]:
#Iterating 1-D array
arr=np.array([1,2,3])
for x in arr:
    print(x)

1
2
3


In [ ]:
#Iterating 2-D array
arr=np.array([[1,2,3],[4,5,6]])
for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [44]:
arr=np.array([[1,2,3],[4,5,6]])
for x in arr:
   for y in x:
       print(y)

1
2
3
4
5
6


In [46]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [47]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [53]:
arr=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
for x in np.nditer(arr):
 print(x)

1
2
3
4
5
6
7
8


In [ ]:
#Iterate through the array as a string:
arr = np.array([1,2,3])

for x in np.nditer(arr,flags=['buffered'], op_dtypes=['S']):
  print(x) 

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


In [63]:
#Iterating with different step size
arr = np.array([[1,2,3,4],[5,6,7,8]])
for x in np.nditer(arr[:, ::2]):
    print(x)

1
3
5
7


In [ ]:
#Enumerated Iteration Using ndenumerate()
arr=np.array([1,2,3])
for idx, x in np.ndenumerate(arr):
    print(idx,x)

 

(0,) 1
(1,) 2
(2,) 3


In [ ]:
# In 2-d array
arr=np.array([[1,2,3,4],[5,6,7,8]])
for idx, x in np.ndenumerate(arr):
 print(idx,x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [67]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [ ]:
#Join two 2-D arrays along rows (axis=1)
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
#Joining Arrays Using Stack Functions
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.stack((arr1,arr2),axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [70]:
#Stacking along Rows
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.hstack((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [71]:
#Stacking Along Columns
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [72]:
#Stacking along Height
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [73]:
#Splitting Numpy Arrays
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [74]:
#If less elements then required
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [3]:
#Searching Arrays
import numpy as np
arr=np.array([1,2,3,4,5,4])
x=np.where(arr==4)
print(x)

(array([3, 5]),)


In [4]:
import numpy as np
arr=np.array([1,2,3,4,5,4])
x=np.where(arr%2==0)
print(x)

(array([1, 3, 5]),)


In [5]:
arr=np.array([1,2,3,4,5,4])
x=np.where(arr%2==1)
print(x)

(array([0, 2, 4]),)


In [ ]:
arr=np.array([1,2,3,4,5,6,8])
x=np.searchsorted(arr,7)
print(x)

6


In [7]:

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


In [8]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7,side='right')

print(x)

2


In [9]:
arr=np.array([1,2,3,4,5,6,8])
x=np.searchsorted(arr,[7,9,3])
print(x)

[6 7 2]


SORTING

In [10]:
arr=np.array([3,2,0,1])
print(np.sort(arr))

[0 1 2 3]


In [11]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [12]:
arr=np.array([True,False,True])
print(np.sort(arr))

[False  True  True]


In [17]:
arr=np.array([[3,2,4],[5,0,1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]
